name: Check the PR content

on:
  push:

jobs:
  check-PR-content:
    name: check-PR-content
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.check-content.outputs.result }}
    steps:
      - name: fetch repository
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-schema-rust
          ref: main
          path: ion-schema-rust-current

      - name: check the last commit content
        id: check-content
        run: |
          cd ion-schema-rust-current
          log=$(git log -1 --raw --name-only)
          modifiedFiles=$(grep wasm-schema-sandbox/ <<< "$log")
          echo $modifiedFileds
          if [[ -z "$modifiedFiles" ]]; then echo "::set-output name=result::fail"; else echo "::set-output name=result::pass"; fi

  build-wasm:
    name: build-wasm
    needs: check-PR-content
    if: ${{ needs.check-PR-content.outputs.output1 == 'pass' }}
    runs-on: ubuntu-latest
    steps:
      - name: fetch-ion-schema-rust
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-schema-rust
          ref: main
          path: ion-schema-rust

      - name: Download wasm
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          cd ion-schema-rust/wasm-schema-sandbox && wasm-pack build --target web

      - name: Upload the files to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wasm-files
          path: |
            ion-schema-rust/wasm-schema-sandbox/pkg/wasm_ion_schema.js
            ion-schema-rust/wasm-schema-sandbox/pkg/wasm_ion_schema_bg.wasm.d.ts
            ion-schema-rust/wasm-schema-sandbox/pkg/wasm_ion_schema_bg.wasm
            ion-schema-rust/wasm-schema-sandbox/pkg/wasm_ion_schema.d.ts

  Create-PR:
    name: Create-PR
    needs: build-wasm
    runs-on: ubuntu-latest
    steps:
      - name: fetch ion schema repository
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-schema
          ref: gh-pages
          path: ion-schema

      - name: Download the files from artifacts
        uses: actions/download-artifact@v2
        with:
          name: wasm-files

      - run: mv -f wasm_ion_schema.d.ts /home/runner/work/ion-schema-rust/ion-schema-rust/ion-schema/assets
      - name: Check the GitHub status and push
        run: |
          cd /home/runner/work/ion-schema-rust/ion-schema-rust/ion-schema
          git status
          git add *
          git commit -m "Upload wasm files."
          git remote -v
          

      

