name: Check the PR content

on:
  push:

jobs:
  check-PR-content:
    name: check-PR-content
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.check-content.outputs.result }}
    steps:
      - name: fetch repository
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-schema-rust
          ref: main
          path: ion-schema-rust-current

      - name: check the last commit content
        id: check-content
        run: |
          cd ion-schema-rust-current
          log=$(git log -1 --raw --name-only)
          modifiedFiles=$(grep wasm-schema-sandbox/ <<< "$log")
          echo $modifiedFileds
          if [[ -z "$modifiedFiles" ]]; then echo "::set-output name=result::fail"; else echo "::set-output name=result::pass"; fi

  build-wasm:
    name: build-wasm
    needs: check-PR-content
    if: ${{ needs.check-PR-content.outputs.output1 == 'pass' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: fetch-ion-schema-rust
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-schema-rust
          ref: main

      - name: Download wasm
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          cd wasm-schema-sandbox && wasm-pack build --target web
          cd /home/runner/work/ion-schema-rust

      - name: fetch ion schema repository
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-schema
          ref: gh-pages
          path: ion-schema

      - name: Moving files to another repository
        run: mv -f /home/runner/work/ion-schema-rust/ion-schema-rust/wasm-schema-sandbox/pkg/wasm_ion_schema.d.ts /home/runner/work/ion-schema-rust/ion-schema-rust/ion-schema/assets

      - name: create PR under ion schema repository
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update wasm files
          title: Update wasm files
          branch: update-wasm-files
          path: /home/runner/work/ion-schema-rust/ion-schema-rust/ion-schema
          base: gh-pages

          
          

